version: '3.4'
services:
  jira:
    image: chinafengzhao/jira-software:8.11.0
    user: root
    container_name: jira-software
    ports:
      - "8080:8080"
    # restart: always
    environment:
      - X_PROXY_NAME:jira.qh-1.cn
      - X_PROXY_PORT:80
      - X_PROXY_SCHEME:http
      #- CATALINA_OPTS='-Xms4096m -Xmx8192m'  
    networks:
      - jira
    depends_on:
      - db
    volumes:
      - /data/jira/jira-data-bak:/var/atlassian/application-data/jira
      - /data/jira/jira-data:/var/atlassian/jira

  db:
    image: mysql:5.7.31
    container_name: jira-db
    networks:
      - jira
    ports:
      - "3308:3306"
    # restart: always
    expose:
      - '3306' 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=qhdata
      - MYSQL_USER=qhdata
      - MYSQL_PASSWORD=password
      - TZ=Asia/Shanghai
    volumes:
      -  /usr/local/mysql-jira/conf/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      -  /usr/local/mysql-jira/data:/var/lib/mysql

networks:
   jira:
      external: true
